[general]
live_config_reload = true
import = [
#     "~/.config/alacritty/themes/themes/nightfox.toml"
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]



[window]
# opacity = 0.85
resize_increments = true
blur = true
dimensions = { columns = 125, lines = 40 }
decorations = "Full"
dynamic_padding = true

[font]
size = 14.0
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }